language: java
jdk:
  - oraclejdk8

sudo: false
env:
  global:
    - secure: "LLqhKxqgRMp/C/TzZWv8YuhpmEm1twggm76NBUAQfZmOPLCkQSpAO8hoBM3qaIlDPSKPgoYj9f0TBuNi0iIFghQf0Xc4pXPCV0AnoGpXwRGiJATTAXfnG7RBa/hXRRBeAKlGmAI9GLtIoCQbUKYhq8gqwbzQVQXq+90rhsMH4zo="
    - CRATE_TESTS_SQL_REQUEST_TIMEOUT="20"
    - _JAVA_OPTIONS="-Xms1g -Xmx1g"


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

before_install:
  - ulimit -u 65535
  - ulimit -n 65536

script:
  - ./gradlew -s test
  - ./gradlew -s itest
  - ./gradlew -s forbiddenApisMain
  - ./gradlew -s pmdMain
  - ./blackbox/.venv/bin/sphinx-build -n -W -c docs/ -b html -E blackbox/docs/ docs/out/html

after_success:
  - ./gradlew jacocoReport
  - bash <(curl -s https://codecov.io/bash)


branches:
  except:
    - /.*\/.*/


addons:
  apt:
    sources:
        - deadsnakes
    packages:
        - python3.4
        - python3.4-dev
        - oracle-java8-installer # use newer java8 then default travis oraclejdk8
  coverity_scan:
    project:
      name: "crate/crate"
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew compileJava"
    notification_email: sysadmin@crate.io
    branch_pattern: coverity_scan
