language: java
jdk:
  - oraclejdk8

sudo: required
env:
  global:
    - secure: "LLqhKxqgRMp/C/TzZWv8YuhpmEm1twggm76NBUAQfZmOPLCkQSpAO8hoBM3qaIlDPSKPgoYj9f0TBuNi0iIFghQf0Xc4pXPCV0AnoGpXwRGiJATTAXfnG7RBa/hXRRBeAKlGmAI9GLtIoCQbUKYhq8gqwbzQVQXq+90rhsMH4zo="
    - CRATE_TESTS_SQL_REQUEST_TIMEOUT="20"
    - CRATE_TESTS_NO_IPV6=true
    - _JAVA_OPTIONS="-Xms1g -Xmx1g"
    - GRADLE_OPTS="-Dorg.gradle.daemon=false"

git:
  submodules: false

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false


before_install:
  - git submodule update --init -- es/upstream

script:
  - ./gradlew -s :sql:test


branches:
  except:
    - /.*\/.*/


addons:
  apt:
    packages:
        - oracle-java8-installer # use newer java8 then default travis oraclejdk8
  coverity_scan:
    project:
      name: "crate/crate"
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew compileJava"
    notification_email: sysadmin@crate.io
    branch_pattern: coverity_scan
