language: java
jdk:
  - openjdk7
  - oraclejdk8

sudo: false
env:
  global:
    - secure: "LLqhKxqgRMp/C/TzZWv8YuhpmEm1twggm76NBUAQfZmOPLCkQSpAO8hoBM3qaIlDPSKPgoYj9f0TBuNi0iIFghQf0Xc4pXPCV0AnoGpXwRGiJATTAXfnG7RBa/hXRRBeAKlGmAI9GLtIoCQbUKYhq8gqwbzQVQXq+90rhsMH4zo="
    - CRATE_TESTS_SQL_REQUEST_TIMEOUT="10"
    - JAVA7_HOME="/usr/lib/jvm/java-7-oracle"
    - _JAVA_OPTIONS="-Xmx1g -XX:MaxPermSize=256m"


before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false

before_install:
  - ulimit -u 65535

script:
  - ./gradlew -PtestForks=2 -s test
  - ./gradlew -s itest
  - ./blackbox/bin/sphinx-build -n -W -c docs/ -b html -E blackbox/docs/ docs/out/html

after_success:
  - ./gradlew jacocoReport
  - bash <(curl -s https://codecov.io/bash)


branches:
  except:
    - /.*\/.*/


addons:
  coverity_scan:
    project:
      name: "crate/crate"
    build_command_prepend: "./gradlew clean"
    build_command:   "./gradlew compileJava"
    notification_email: sysadmin@crate.io
    branch_pattern: coverity_scan
