name: Check PR Author has signed CLA
on:
  pull_request:
    types: [opened, synchronize, unlabeled]
jobs:
  check-author-signed-cla:
    uses: crate/cla-check/.github/workflows/cla-check-workflow.yml@main
    # with: 
      # simulate_no_cla: true
    secrets: inherit
